# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build features

on:
  push:
    branches: feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pull and checkout from git repository
        run: |
          echo "pulling and checking out from git repository"
      
      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install npm packages
        run: npm install
      
      - name: Update Angular
        run: npm install -g @angular/cli@latest
      
      - name: Run tests
        run: |
          ng test --watch=false
          ng build --prod
          echo "running tests and build angular app"
      
      - name: Build
        run: ng build --prod
